---
- name: resolve platform specific vars
  include_vars: '{{item}}'
  with_first_found:
    - files:
        - '{{ansible_distribution}}-{{ansible_distribution_release}}.yml'
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
      skip: true
      paths:
        - '{{role_path}}/vars'

- name: download tgz...
  become: yes
  become_user: root
  get_url:
    headers: Cookie:oraclelicense=accept-securebackup-cookie
    url: '{{java_oracle_tgz_url}}'
    dest: /tmp/{{java_oracle_tgz}}
    mode: 0644

- name: unarchive....
  become: yes
  become_user: root
  unarchive:
    copy: no
    src: /tmp/{{java_oracle_tgz}}
    dest: '{{java_oracle_parent_install_dir}}'
    creates: '{{java_oracle_install_dir}}'

- name: link....
  become: yes
  become_user: root
  file:
    src: '{{java_oracle_install_dir}}'
    dest: '{{java_oracle_link_dir}}'
    state: link

- name: add to default path and ease systemd integration...
  become: yes
  become_user: root
  with_items:
    - f: java-oracle.sh
      d: /etc/profile.d
    - f: java-oracle.env
      d: '{{java_oracle_install_dir}}'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}|default("0644")}}'
